class Error(Exception):
    pass


class UserError(Error):
    pass
